version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: mysuperdata
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mysuperdata"]
      interval: 3s
      timeout: 2s
      retries: 10

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    entrypoint: ["/entrypoint.sh"]
